"use client";
export const PRODUCTS_ACTION_TYPES = {
  FETCH_PRODUCTS_START: "products/FETCH_PRODUCTS_START",
  ETCH_PRODUCTS_START1: "products/fetchProductsStart1",
  FETCH_PRODUCTS_SUCCESS: "products/FETCH_PRODUCTS_SUCCESS",
  FETCH_PRODUCTS_FAILED: "products/FETCH_PRODUCTS_FAILED",
};
